# Generated by Django 4.1.5 on 2023-04-12 22:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_client_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="USAStates",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statefp", models.CharField(max_length=2)),
                ("statens", models.CharField(max_length=8)),
                ("affgeoid", models.CharField(max_length=11)),
                ("geoid", models.CharField(max_length=2)),
                ("stusps", models.CharField(max_length=2)),
                ("name", models.CharField(max_length=100)),
                ("lsad", models.CharField(max_length=2)),
                ("aland", models.BigIntegerField()),
                ("awater", models.BigIntegerField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
            options={
                "verbose_name": "USA States 2018",
            },
        ),
    ]
