name: Leak Survey Mapping CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-vm:
    # spin up Ubuntu version 22.04
    runs-on: ubuntu-22.04
    steps:
      # Selects an action to run as part of a step in your job. An action is a reusable unit of code.
      - uses: actions/checkout@v3   
      - run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
    
