name: Leak Survey Mapping CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-vm:
    # spin up Ubuntu version 22.04
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        working-directory: scripts
    steps:
    - uses: actions/checkout@v3
    
